# Generated by Django 4.2.4 on 2023-08-18 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hrate',
            field=models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(52), django.core.validators.MaxValueValidator(82)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(92)]),
        ),
    ]
